"""Top-level export_to_python orchestration."""

import re
from engine.graph_builder import (
    GAN_NOISE_TYPE, SUBGRAPH_TYPE, build_modules, topological_sort,
)
from training import detect_training_mode
from export.datasets import _generate_dataset_code
from export.helpers import _get_data_node, _get_loss_node, _get_optimizer_props, _get_optimizer_type
from export.model import _generate_model_class, _generate_subgraph_class
from export.templates import _POSITIONAL_ENCODING_CLASS, _TOKENIZER_CLASS
from export.training_loops import _autoregressive_training_loop, _diffusion_training_loop, _gan_training_loop, _standard_classification_loop, _standard_reconstruction_loop, _vae_training_loop

# ─── Main export function ─────────────────────────────────────────────────────

def export_to_python(graph_data: dict) -> str:
    """Generate a standalone Python file from a NodeTorch graph.

    Args:
        graph_data: Serialized graph in NodeTorch format { version, graph: { nodes, edges } }

    Returns:
        Complete, runnable Python file as a string.
    """
    graph = graph_data["graph"]
    nodes_list = graph["nodes"]
    edges = graph["edges"]
    graph_name = graph.get("name", "Model")

    nodes = {n["id"]: n for n in nodes_list}
    order = topological_sort(nodes, edges)

    # Build modules to resolve actual dimensions
    try:
        modules = build_modules(graph_data)
    except Exception:
        modules = {}

    # Detect training paradigm
    training_mode = detect_training_mode(nodes)

    # Find key nodes
    data_node = _get_data_node(nodes)
    loss_node = _get_loss_node(nodes)
    opt_props = _get_optimizer_props(nodes)
    opt_type = _get_optimizer_type(nodes)

    # ─── Generate subgraph classes ────────────────────────────────────────────
    subgraph_classes: dict[str, str] = {}  # node_id -> class_name
    subgraph_code_blocks: list[str] = []

    for nid in order:
        n = nodes[nid]
        if n["type"] == SUBGRAPH_TYPE and n.get("subgraph"):
            code = _generate_subgraph_class(n, modules, modules)
            block_name = n.get("properties", {}).get("blockName", "Block")
            class_name = re.sub(r'[^a-zA-Z0-9]', '', block_name)
            if not class_name:
                class_name = "Block"
            subgraph_classes[nid] = class_name
            subgraph_code_blocks.append(code)

    # ─── Generate model class ─────────────────────────────────────────────────

    if training_mode == "gan":
        # GAN: Generator and Discriminator are subgraph blocks, no main Model class
        model_code = ""
    else:
        model_code = _generate_model_class(order, nodes, edges, modules, training_mode, subgraph_classes)

    # ─── Generate training loop ───────────────────────────────────────────────

    if training_mode == "gan":
        training_code = _gan_training_loop(graph_data, modules)
    elif training_mode == "diffusion":
        training_code = _diffusion_training_loop(graph_data, modules)
    elif training_mode == "autoregressive":
        training_code = _autoregressive_training_loop(opt_props, opt_type)
    elif loss_node and loss_node["type"] == "ml.loss.vae":
        loss_props = loss_node.get("properties", {})
        training_code = _vae_training_loop(opt_props, opt_type, loss_props)
    elif loss_node and loss_node["type"] == "ml.loss.mse":
        # Check if it's actually diffusion (MSE used for noise prediction)
        training_code = _standard_reconstruction_loop(opt_props, opt_type)
    else:
        training_code = _standard_classification_loop(opt_props, opt_type, loss_node)

    # ─── Assemble the complete file ───────────────────────────────────────────

    sections: list[str] = []

    # Header
    sections.append(f'"""')
    sections.append(f'{graph_name}')
    sections.append(f'Generated by NodeTorch — https://github.com/wilsonzeng/nodetorch')
    sections.append(f'')
    sections.append(f'A standalone, runnable training script.')
    sections.append(f'Run: python {graph_name.replace(" ", "_").lower()}.py')
    sections.append(f'"""')
    sections.append("")

    # Imports
    sections.append("import torch")
    sections.append("import torch.nn as nn")
    sections.append("import torchvision")
    sections.append("import torchvision.transforms as transforms")
    sections.append("")

    # Device
    sections.append("# --- Device selection ---")
    sections.append("")
    sections.append("if torch.cuda.is_available():")
    sections.append("    device = torch.device('cuda')")
    sections.append("elif hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():")
    sections.append("    device = torch.device('mps')")
    sections.append("else:")
    sections.append("    device = torch.device('cpu')")
    sections.append("print(f'Using device: {device}')")
    sections.append("")

    # Dataset — check if a BPE tokenizer node is in the graph
    tokenizer_type = None
    tokenizer_config = None
    for n in nodes.values():
        nt = n.get("type", "")
        if nt.startswith("ml.preprocessing.tokenizer_"):
            tokenizer_type = nt
            tokenizer_config = n.get("properties", {})
            break

    if data_node:
        if tokenizer_type == "ml.preprocessing.tokenizer_bpe":
            sections.append(_generate_dataset_code(data_node, bpe_config=tokenizer_config))
        else:
            sections.append(_generate_dataset_code(data_node))
        sections.append("")

    # Subgraph classes
    if subgraph_code_blocks:
        sections.append("")
        sections.append("# --- Network blocks ---")
        sections.append("")
        for block_code in subgraph_code_blocks:
            sections.append(block_code)
            sections.append("")

    # Model class (not for GAN — subgraph blocks serve as models)
    if model_code:
        sections.append("")
        sections.append("# --- Model ---")
        sections.append("")
        # Inject helper classes used by the model
        if "Tokenizer(" in model_code:
            sections.append(_TOKENIZER_CLASS)
            sections.append("")
        if "PositionalEncoding(" in model_code:
            sections.append(_POSITIONAL_ENCODING_CLASS)
            sections.append("")
        sections.append(model_code)
        sections.append("")

    # Training loop
    sections.append("")
    sections.append("# --- Training ---")
    sections.append("")
    sections.append(training_code)
    sections.append("")

    # Main
    sections.append("")
    sections.append("# --- Entry point ---")
    sections.append("")
    sections.append('if __name__ == "__main__":')
    if training_mode == "gan":
        sections.append("    generator, discriminator = train()")
        sections.append("    # Generate samples from trained GAN")
        latent_dim = 100
        for n in nodes.values():
            if n["type"] == GAN_NOISE_TYPE:
                latent_dim = n.get("properties", {}).get("latentDim", 100)
        sections.append(f"    noise = torch.randn(16, {latent_dim}, device=device)")
        sections.append("    with torch.no_grad():")
        sections.append("        generated = generator(noise)")
        sections.append("    print(f'Generated images shape: {generated.shape}')")
    elif training_mode == "diffusion":
        sections.append("    model, scheduler = train()")
        sections.append("    # Generate samples by denoising")
        sections.append("    samples = sample(model, scheduler, num_samples=16)")
        sections.append("    print(f'Generated samples shape: {samples.shape}')")
    elif loss_node and loss_node["type"] == "ml.loss.vae":
        sections.append("    model = train()")
        sections.append("    # Generate by sampling from latent space")
        sections.append("    with torch.no_grad():")
        sections.append("        z = torch.randn(16, 32, device=device)  # sample from N(0,1)")
        sections.append("        # Pass z through decoder (requires adapting the model)")
        sections.append("        print('VAE training complete. See model for encoding/decoding.')")
    elif loss_node and loss_node["type"] == "ml.loss.mse":
        # Reconstruction (autoencoder): report MSE, no accuracy
        sections.append("    model = train()")
        sections.append("    # Evaluate reconstruction MSE on test set")
        sections.append("    model.eval()")
        sections.append("    total_mse = 0.0")
        sections.append("    n_batches = 0")
        sections.append("    criterion_eval = nn.MSELoss()")
        sections.append("    with torch.no_grad():")
        sections.append("        for images, _ in test_loader:")
        sections.append("            images = images.to(device)")
        sections.append("            outputs = model(images)")
        sections.append("            total_mse += criterion_eval(outputs, images).item()")
        sections.append("            n_batches += 1")
        sections.append("    print(f'Test reconstruction MSE: {total_mse / max(n_batches, 1):.4f}')")
    elif data_node and data_node["type"] == "data.tiny_shakespeare":
        # Autoregressive language model: report perplexity, skip accuracy
        sections.append("    import math")
        sections.append("    model = train()")
        sections.append("    # Evaluate perplexity on held-out sequences")
        sections.append("    model.eval()")
        sections.append("    total_loss = 0.0")
        sections.append("    n_tokens = 0")
        sections.append("    criterion_eval = nn.CrossEntropyLoss(reduction='sum')")
        sections.append("    with torch.no_grad():")
        sections.append("        for inputs, targets in test_loader:")
        sections.append("            inputs, targets = inputs.to(device), targets.to(device)")
        sections.append("            logits = model(inputs)")
        sections.append("            B, S, V = logits.shape")
        sections.append("            total_loss += criterion_eval(logits.reshape(B*S, V), targets.reshape(B*S)).item()")
        sections.append("            n_tokens += B * S")
        sections.append("    avg = total_loss / max(n_tokens, 1)")
        sections.append("    print(f'Test perplexity: {math.exp(min(avg, 20)):.2f}')")
    else:
        sections.append("    model = train()")
        sections.append("    # Evaluate on test set")
        sections.append("    model.eval()")
        sections.append("    correct = 0")
        sections.append("    total = 0")
        sections.append("    with torch.no_grad():")
        sections.append("        for images, labels in test_loader:")
        sections.append("            images, labels = images.to(device), labels.to(device)")
        sections.append("            outputs = model(images)")
        sections.append("            _, predicted = outputs.max(1)")
        sections.append("            total += labels.size(0)")
        sections.append("            correct += predicted.eq(labels).sum().item()")
        sections.append("    print(f'Test accuracy: {100.0 * correct / total:.1f}%')")
    sections.append("")

    return '\n'.join(sections)
